label: Feature request
description: Suggest an idea for the game (content, modding capabilities, etc...)
title: "[Feature] "
labels: [issue/feature, request]
body:
  - type: textarea
    id: is-related
    attributes:
      label: Is your feature request related to a problem (if not, explain why you think this feature should be added)? Please describe.
      description: |
        A clear and concise description of what the problem is. (example: "I'm always frustrated when [...]" or "This should be added because it would make it easierfor people to do X..").
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.
